<table id="maintable" class="table table-striped"  style="width:100%">
    <thead>
        <tr>
            <th>#</th>
            <th>Gasto</th>
            <th>Iva</th>
            <th>Descuento</th>
            <th>Importe</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>placeholder</td>
            <td>placeholder</td>
            <td>placeholder</td>
            <td>placeholder</td>
            <td>placeholder</td>
        </tr>
    </tbody>
</table>